# Generated by Django 5.2 on 2025-05-13 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='data',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='data',
            new_name='criado_em',
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marcacao',
            name='status',
            field=models.CharField(choices=[('por_marcar', 'Por Marcar'), ('marcada', 'Marcada'), ('cancelada', 'Cancelada')], default='por_marcar', max_length=20),
        ),
        migrations.AlterField(
            model_name='aula',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.aula'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.aula'),
        ),
    ]
