# Generated by Django 5.2 on 2025-05-17 21:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_remove_aula_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcacao',
            old_name='atleta',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='marcacao',
            unique_together={('aula', 'user')},
        ),
    ]
