# Generated by Django 5.2 on 2025-05-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_rename_atleta_marcacao_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='participantes_atual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
