# Generated by Django 5.2 on 2025-05-18 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_aula_participantes_atual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nota',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='aulas.aula'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='comentario',
            unique_together={('aula', 'autor')},
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
