<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
# Generated by Django 5.2 on 2025-05-15 15:59
=======
# Generated by Django 5.2 on 2025-05-15 14:48
>>>>>>> Stashed changes
=======
# Generated by Django 5.2 on 2025-05-15 14:48
>>>>>>> Stashed changes
=======
# Generated by Django 5.2 on 2025-05-15 14:48
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagem',
            field=models.ImageField(blank=True, default='imagens_perfil/default.png', null=True, upload_to='imagens_perfil/'),
        ),
    ]
