# Generated by Django 5.2 on 2025-05-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_chat_status_chat_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(),
        ),
    ]
