# Generated by Django 5.2 on 2025-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_chat_status_chat_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
