# Generated by Django 5.2 on 2025-05-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_chat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='status',
        ),
    ]
