# Generated by Django 5.2 on 2025-05-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_chat_status'),
        ('database', '0004_remove_chat_status_chat_participants_and_more'),
    ]

    operations = [
    ]
