# Generated by Django 5.2 on 2025-05-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_merge_20250517_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.JSONField(default=list),
        ),
    ]
