# Generated by Django 5.2 on 2025-05-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_merge_20250515_1811'),
        ('database', '0006_alter_chat_avatar_alter_chat_name_and_more'),
    ]

    operations = [
    ]
